spring.application.name=photography-backend
# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/photography_db
spring.datasource.username=photography_user
spring.datasource.password=NikkiCooper6290!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

